username: 
password: 
phone_number: 

positions:
- Data Scientist
- # Another position you want to search for
- # A third position you want to search for

locations:
- Remote
- # A second location you want to search in 

# --------- Optional Parameters -------
# uploads:
#  Resume: 32
#  Cover Letter: 45
#  Photo: 67


# output_filename: PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore